import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

import Slider from "../components/Slider.js"

import armaflex from "../photos/armaflex.jpeg"

import { Container, Row, Col } from 'reactstrap';


export default function Home() {
  return (
    <div>
      <Head>
        <title>Julian Ayllon</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>



      <Row>
        <Slider />
      </Row>

      {/* <Image src={armaflex} layout="responsive" height="1000" width="" alt="green" /> */}





      {/* ----------------------------------------------------------------------------------------------------------------------- */}


      <Row style={{ backgroundColor: "indigo", height: "", padding: "0", margin: "0" }}>


        <Row style={{ backgroundColor: "black", padding: "0", margin: "0", height: "20vh" }}>
          <Col style={{ backgroundColor: "red", display: "flex", alignItems: "center", padding: "0", margin: "0" }}><h1 style={{ backgroundColor: "orange", margin: "auto" }}>MECHANICAL INSULATION SOLUTIONS</h1></Col>
          <Col style={{ backgroundColor: "blue", padding: "0", margin: "0", display: "flex", alignItems: "center" }}><p style={{ backgroundColor: "orange", margin: "0", padding: "5px", fontSize: "20px", lineHeight: "45px", width: "80%" }}>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Laudantium, suscipit. sit amet consectetur sit amet adipisicing elit. Laudantium, suscipit. sit amet consectetur elit.</p></Col>
        </Row>

        <Row style={{ backgroundColor: "white", padding: "0", margin: "0" }}>
          <Col lg="10" style={{ marginLeft: "auto", marginRight: "auto", backgroundColor: "" }}>
            <Row>
              <Col style={{ backgroundColor: "orange" }}>
                <Row style={{ backgroundColor: "pink", textAlign: "center" }}><h1>hello</h1></Row>
                <Row style={{ padding: "35px" }}><Image src={armaflex} layout="" height="" width="" alt="green" /></Row>
              </Col>
              <Col style={{ backgroundColor: "blue" }}>
                <Row style={{ backgroundColor: "grey", textAlign: "center" }}><h1>hello</h1></Row>
                <Row style={{ padding: "35px" }}><Image src={armaflex} layout="" height="" width="" alt="green" /></Row>
              </Col>
              <Col style={{ backgroundColor: "black" }}>
                <Row style={{ backgroundColor: "pink", textAlign: "center" }}><h1>hello</h1></Row>
                <Row style={{ padding: "35px" }}><Image src={armaflex} layout="" height="" width="" alt="green" /></Row>
              </Col>
            </Row>
          </Col>
        </Row>


      </Row>


      {/* ----------------------------------------------------------------------------------------------------------------------- */}





      <Row className={styles.counterBackground}>

        <Col lg="10" style={{ margin: "auto", padding: "0" }}>


          <Row style={{ color: "white", textAlign: "center", backgroundColor: "", paddingTop: "50px", margin: "0" }}>
            <header style={{ fontSize: "30px", fontWeight: "400", letterSpacing: "4px", padding: "20px" }}>ABOUT US</header>
            <h1 style={{ lineHeight: "1.2", fontWeight: "800", fontSize: "50px", paddingBottom: "20px" }}>Providing all kinds <br /> of construction services</h1>
            <p style={{ fontSize: "25px", lineHeight: "2.2", fontWeight: "300", padding: "30px", backgroundColor: "" }}>Our construction company has been founded 10 years ago, at the very peak of the building frenzy in the US…<br /> Since then we’ve built hundreds of commercial, government and private buildings and facilities. It may not sound like a lot, but if you estimate the,<br /> working hours, materials, planning and correlating that were all involved in completing each separate project, then our productivity is immense!</p>
          </Row>



          <Row style={{ backgroundColor: "", margin: "0", padding: "0" }}>



            <Row id="counter" style={{ padding: "0", margin: "0" }}>


              <Col style={{ backgroundColor: "", padding: "0", margin: "0" }}>
                <Row id="num" data-value="26" style={{ backgroundColor: "", justifyContent: "center", fontSize: "90px", margin: "0", color: "blue", fontWeight: "800", lineHeight: "1.3" }}>
                  0
        </Row>
                <Row style={{ backgroundColor: "", justifyContent: "center", fontSize: "32px", color: "white", fontWeight: "800", lineHeight: "2" }}>
                  Years on the Market
        </Row>
              </Col>

              <Col style={{ backgroundColor: "", padding: "0", margin: "0" }}>
                <Row id="num" data-value="4" style={{ backgroundColor: "", justifyContent: "center", fontSize: "90px", margin: "0", color: "blue", fontWeight: "800", lineHeight: "1.3" }}>
                  0
        </Row>
                <Row style={{ backgroundColor: "", justifyContent: "center", fontSize: "32px", margin: "0", color: "white", fontWeight: "800", lineHeight: "2" }}>
                  Operational Brigades
        </Row>
              </Col>

              <Col style={{ backgroundColor: "", padding: "0", margin: "0" }}>
                <Row id="num" data-value="378" style={{ backgroundColor: "", justifyContent: "center", fontSize: "90px", margin: "0", color: "blue", fontWeight: "800", lineHeight: "1.3" }}>
                  0
        </Row>
                <Row style={{ backgroundColor: "", justifyContent: "center", fontSize: "32px", color: "white", fontWeight: "800", lineHeight: "2" }}>
                  Units Engineering
        </Row>
              </Col>

              <Col style={{ backgroundColor: "", padding: "0", margin: "0" }}>
                <Row id="num" data-value="400" style={{ backgroundColor: "", justifyContent: "center", fontSize: "90px", margin: "0", color: "blue", fontWeight: "800", lineHeight: "1.3" }}>
                  0
        </Row>
                <Row style={{ backgroundColor: "", justifyContent: "center", fontSize: "32px", color: "white", fontWeight: "800", lineHeight: "2" }}>
                  Employees of the company
        </Row>
              </Col>


            </Row>




            <Row style={{ backgroundColor: "", padding: "0", margin: "0", justifyContent: "center", padding: "100px" }}>
              <button style={{ width: "280px", height: "80px", backgroundColor: "blue", color: "white", fontSize: "25px", fontWeight: "500" }}>MORE INFO</button>
            </Row>



          </Row>



        </Col>


      </Row>



      {/* ----------------------------------------------------------------------------------------------------------------------- */}


      {/*-------------------------- what we offer our clients 3 */}
      <Row style={{ backgroundColor: "orange", height: "calc(100vh - 160px)", padding: "0", margin: "0" }}>


        <header style={{ display: "", backgroundColor: "green", textAlign: "center", paddingTop: "90px", paddingBottom: "300px" }}>
          {/* Mechanical Insulation Solutions */}


          <h1 style={{ fontSize: "60px", letterSpacing: "1.5px" }}>What we offer to our clients</h1>

          <p style={{ fontSize: "20px", padding: "20px" }}>Lorem ipsum dolor sit amet consectetur, adipisicing. Doloremque, officia.</p>




        </header>





        {/*------- 3 images ------*/}
        <div style={{ backgroundColor: "blue" }}>

          <Row>
            <Col>
              <Image src={armaflex} layout="responsive" height="700" width="" alt="green" />
            </Col>
            <Col>
              <Image src={armaflex} layout="responsive" height="700" width="" alt="green" />
            </Col>
            <Col>
              <Image src={armaflex} layout="responsive" height="700" width="" alt="green" />
            </Col>

          </Row>


        </div>








      </Row>





          {/*-------------------------- services */}
          <div style={{ paddingBottom: "100px" }}>

            <Col style={{ borderTop: "1px solid grey", height: "40vh", paddingTop: "60px", paddingBottom: "60px", backgroundColor: "white" }}>

              <Row style={{ backgroundColor: "", width: "80%", margin: "auto", height: "50%" }}>
                <Col style={{ display: "flex" }}>
                  <Col lg="3" style={{ backgroundColor: "", margin: "auto", textAlign: "right" }}><Image src={armaflex} alt="safety" width={100} height={100} /></Col>
                  <Col style={{ backgroundColor: "", margin: "auto" }}><h1>Abatement</h1><p style={{ fontSize: "20px" }}>Asbestos, lead, and mold abatement and remediation services.</p></Col>
                </Col>

                <Col style={{ display: "flex" }}>
                  <Col lg="3" style={{ backgroundColor: "", margin: "auto", textAlign: "right" }}><Image src={armaflex} alt="safety" width={100} height={100} /></Col>
                  <Col style={{ backgroundColor: "", margin: "auto" }}><h1>Re-Insulation</h1><p style={{ fontSize: "20px" }}>Asbestos, lead, and mold abatement and remediation services.</p></Col>
                </Col>

                <Col style={{ display: "flex" }}>
                  <Col lg="3" style={{ backgroundColor: "", margin: "auto", textAlign: "right" }}><Image src={armaflex} alt="safety" width={100} height={100} /></Col>
                  <Col style={{ backgroundColor: "", margin: "auto" }}><h1>Demolition</h1><p style={{ fontSize: "20px" }}>Asbestos, lead, and mold abatement and remediation services.</p></Col>
                </Col>
              </Row>

              <Row style={{ backgroundColor: "", width: "80%", margin: "auto", height: "50%" }}>
                <Col style={{ display: "flex" }}>
                  <Col lg="3" style={{ backgroundColor: "", margin: "auto", textAlign: "right" }}><Image src={armaflex} alt="safety" width={100} height={100} /></Col>
                  <Col style={{ backgroundColor: "", margin: "auto" }}><h1>Construction</h1><p style={{ fontSize: "20px" }}>Asbestos, lead, and mold abatement and remediation services.</p></Col>
                </Col>

                <Col style={{ display: "flex" }}>
                  <Col lg="3" style={{ backgroundColor: "", margin: "auto", textAlign: "right" }}><Image src={armaflex} alt="safety" width={100} height={100} /></Col>
                  <Col style={{ backgroundColor: "", margin: "auto" }}><h1>Carting</h1><p style={{ fontSize: "20px" }}>Asbestos, lead, and mold abatement and remediation services.</p></Col>
                </Col>

                <Col style={{ display: "flex" }}>
                  <Col lg="3" style={{ backgroundColor: "", margin: "auto", textAlign: "right" }}><Image src={armaflex} alt="safety" width={100} height={100} /></Col>
                  <Col style={{ backgroundColor: "", margin: "auto" }}><h1>Consulting</h1><p style={{ fontSize: "20px" }}>Asbestos, lead, and mold abatement and remediation services.</p></Col>
                </Col>
              </Row>

            </Col>
          </div>





















          {/*-------------------------------2 images */}
          <div className="image-row">
            <a href="/projects">
              <div className={styles.container}>
                <img style={{ width: "100%", height: "100%", padding: "20px" }} src="https://d3cl79h6n1fe0x.cloudfront.net/wp-content/uploads/2020/01/15085115/11.jpeg" alt="" />
                <div className={styles.overlay}>
                  <div className={styles.text}>
                    <div>
                      <h1>Solutions</h1>
                      <p>Heavy foundations</p>
                    </div>
                    <div>
                      <h1>Markets</h1>
                      <p>Institutional/Sports entertainment</p>
                    </div>
                    <div>
                      <h1>Techniques</h1>
                      <p>Drilled shafts</p>
                    </div>
                  </div>
                </div>
              </div>
            </a>
            <a href="/projects">
              <div className={styles.container}>
                <img style={{ width: "100%", height: "100%", padding: "20px" }} src="https://d3cl79h6n1fe0x.cloudfront.net/wp-content/uploads/2020/01/15085115/11.jpeg" alt="" />
                <div className={styles.overlay}>
                  <div className={styles.text}>
                    <div>
                      <h1>Solutions</h1>
                      <p>Heavy foundations</p>
                    </div>
                    <div>
                      <h1>Markets</h1>
                      <p>Institutional/Sports entertainment</p>
                    </div>
                    <div>
                      <h1>Techniques</h1>
                      <p>Drilled shafts</p>
                    </div>
                  </div>
                </div>
              </div>
            </a>
          </div>


          {/* image description */}
          <div className="image-description" style={{ paddingTop: "2%", backgroundColor: "whitesmoke" }}>
            <a href="/projects">
              <div className={styles.container} style={{ paddingLeft: "20px", paddingRight: "20px" }}>
                <h1 style={{ paddingBottom: "15px" }}>Port Everglades Southport Turning Notch</h1>
                <text style={{ paddingTop: "2%" }}><svg style={{ paddingRight: "6px" }} xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-geo-alt-fill" viewBox="0 0 16 16"><path d="M8 16s6-5.686 6-10A6 6 0 0 0 2 6c0 4.314 6 10 6 10zm0-7a3 3 0 1 1 0-6 3 3 0 0 1 0 6z" /></svg>Calgary, Alberta, Canada</text>
                <br />
                <br />
                <br />
                <br />
                <div className={styles.colorborder} style={{ width: "100%", borderBottom: "2px solid black", color: "whitesmoke" }}></div>
              </div>
            </a>
            <a href="/projects">
              <div className={styles.container} style={{ paddingLeft: "20px", paddingRight: "20px" }}>
                <h1 style={{ paddingBottom: "15px" }}>Calgary Zoo - Canadian Wild's Bugtopia</h1>
                <text style={{ paddingTop: "2%" }}><svg style={{ paddingRight: "6px" }} xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-geo-alt-fill" viewBox="0 0 16 16"><path d="M8 16s6-5.686 6-10A6 6 0 0 0 2 6c0 4.314 6 10 6 10zm0-7a3 3 0 1 1 0-6 3 3 0 0 1 0 6z" /></svg>Broward County, Florida</text>
                <br />
                <br />
                <br />
                <br />
                <div className={styles.colorborder} style={{ width: "100%", borderBottom: "2px solid black" }}></div>
              </div>
            </a>
          </div>











          {/*-------------------------- markets we serve */}
          <div style={{ backgroundColor: "whitesmoke", display: "flex", height: "", paddingTop: "80px", paddingBottom: "80px" }}>

            <Col xs="4" sm="4" md="4" lg="4" xl="4" xxl="4" className={styles.left} style={{ backgroundColor: "", marginLeft: "auto", padding: "25px" }}>
              <div style={{ backgroundColor: "", height: "100%" }}>
                <h1 style={{ color: "blue" }}>Markets we serve</h1>
                <br />
                <p style={{ fontSize: "30px", width: "60%" }}>Keller has experience across many markets througout the construction industry and understand the unique challanges and...</p>
                <br />
                <br />
                <p style={{ color: "blue" }}>Learn more --></p>

              </div>
            </Col>

            <Col xs="4" sm="4" md="4" lg="4" xl="4" xxl="4" className={styles.right} style={{ backgroundColor: "", marginRight: "auto" }}>
              <div style={{ backgroundColor: "", height: "100%" }}>
                <h1 style={{ color: "blue" }}>Our expertise</h1>

                <br />
                <p style={{ fontSize: "30px", width: "60%" }}>Keller is able to tap into a wealth of experience, and using proven, best practice methods offer a wide range of...</p>
                <br />
                <br />
                <p style={{ color: "blue" }}>Learn more --></p>
              </div>
            </Col>

          </div>






















    </div>
  )
}